Pin GitHub Actions to ubuntu-22.04 for libngram-dev availability
The libngram-dev package is only available in Ubuntu 22.04+, not in
ubuntu-latest (which was Ubuntu 20.04). This fixes the package install
error: 'Unable to locate package libngram-dev'.